"""initial_schema

Revision ID: 0759df99abf0
Revises: 
Create Date: 2026-09-23 17:56:53.841825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0759df99abf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_normalized_name'), 'cities', ['normalized_name'], unique=False)
    op.create_table('destinations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_m', sa.Float(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('accessibility', sa.String(), nullable=True),
    sa.Column('nearest_airport', sa.String(), nullable=True),
    sa.Column('nearest_railway_station', sa.String(), nullable=True),
    sa.Column('nearest_major_city', sa.String(), nullable=True),
    sa.Column('road_connectivity', sa.String(), nullable=True),
    sa.Column('budget_daily_low', sa.Integer(), nullable=True),
    sa.Column('budget_daily_high', sa.Integer(), nullable=True),
    sa.Column('midrange_daily_low', sa.Integer(), nullable=True),
    sa.Column('midrange_daily_high', sa.Integer(), nullable=True),
    sa.Column('luxury_daily_low', sa.Integer(), nullable=True),
    sa.Column('luxury_daily_high', sa.Integer(), nullable=True),
    sa.Column('trip_types', sa.JSON(), nullable=True),
    sa.Column('activities_available', sa.JSON(), nullable=True),
    sa.Column('best_seasons', sa.JSON(), nullable=True),
    sa.Column('ideal_for', sa.JSON(), nullable=True),
    sa.Column('minimum_days', sa.Integer(), nullable=True),
    sa.Column('ideal_days', sa.Integer(), nullable=True),
    sa.Column('maximum_days', sa.Integer(), nullable=True),
    sa.Column('food_scene', sa.Text(), nullable=True),
    sa.Column('local_cuisine', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('ix_destinations_normalized_name'), 'destinations', ['normalized_name'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('destination', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('suitable_for', sa.JSON(), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('best_time', sa.JSON(), nullable=True),
    sa.Column('walking_level', sa.String(), nullable=True),
    sa.Column('indoor_outdoor', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_destination'), 'places', ['destination'], unique=False)
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.create_index(op.f('ix_places_name'), 'places', ['name'], unique=False)
    op.create_table('restaurants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.String(), nullable=True),
    sa.Column('price_level', sa.String(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('is_pure_veg', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_city'), 'restaurants', ['city'], unique=False)
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.create_index(op.f('ix_restaurants_name'), 'restaurants', ['name'], unique=False)
    op.create_index(op.f('ix_restaurants_normalized_name'), 'restaurants', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_normalized_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_city'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_places_name'), table_name='places')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_index(op.f('ix_places_destination'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_destinations_normalized_name'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_cities_normalized_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
